name: push
# 指定此工作流程的触发器
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  # 定义名称为"image-build"的job
  image-build:
    runs-on: self-hosted
    steps:
      # 获取最新变动
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: lmake image
